server:
  port: 8899


spring:
  kafka:
    bootstrap-servers: 192.168.33.128:9092
    consumer:
      enable-auto-commit: false
      group-id: ws-group
      auto-offset-reset: earliest
      #批量消费，每次最多消费多少条数据
      max-poll-records: 5
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties.session.timeout.ms: 30000
      properties.request.timeout.ms: 60000
    producer:
      retries: 3
      acks: 1
      #批量提交大小：5kb
#      batch-size: 5120
#      properties.linger.ms: 1000
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer


#spring:
#  profiles:
#    active: ws
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/ws_cron?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
#    username: root
#    password: root
#    hikari:
#      minimum-idle: 5
#      # 空闲连接存活最大时间，默认600000（10分钟）
#      idle-timeout: 180000
#      # 连接池最大连接数，默认是10
#      maximum-pool-size: 10
#      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
#      auto-commit: true
#      # 连接池名称
#      pool-name: MyHikariCP
#      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#      max-lifetime: 1800000
#      # 数据库连接超时时间,默认30秒，即30000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true

